<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // Import the DB facade
use Illuminate\Support\Facades\Hash; // Import the Hash facade

class StudentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('students')->insert([
            [
                'first_name' => 'andre',
                'second_name' => 'iniesta',
                'gender' => 'male',
                'department' => 'cs',
                'adm_no' => '1345',
                'dob' => '1992-04-11',
                'phone' => '5689234567',
                'email' => 'andreiniesta@gmail.com',
                'password' => Hash::make('password'),
                'distance' => '40',
                'house' => '12B',
                'street' => 'kolathara',
                'post' => 'kolathara',
                'district' => 'kozhikode',
                'state' => 'kerala',
                'country' => 'india',
                'guardian' => 'mustafa',
                'guardian_phone' => '898989898989',
                'pwd' => 'no',
                'course_duration' => '2',
                'adm_date' => '2023-07-19',
                'course_type' => 'pg',
                'reservation' => 'obc',
                'image' => 'users/img/profile/1815121959-andre.jpg',
            ],

            [
                'first_name' => 'abhi',
                'second_name' => 'rajan',
                'gender' => 'male',
                'department' => 'cs',
                'adm_no' => '1305',
                'dob' => '1997-08-22',
                'phone' => '9090909090',
                'email' => 'abhirajan@gmail.com',
                'password' => Hash::make('password'),
                'distance' => '30',
                'house' => 'meleparamb',
                'street' => 'kunnamangalam',
                'post' => 'kunnamangalam',
                'district' => 'kozhikode',
                'state' => 'kerala',
                'country' => 'india',
                'guardian' => 'rajan',
                'guardian_phone' => '8908908907',
                'pwd' => 'no',
                'course_duration' => '2',
                'adm_date' => '2023-07-26',
                'course_type' => 'pg',
                'reservation' => 'obc',
                'image' => 'users/img/profile/1915121959-abhi.jpg',
            ],

            [
                'first_name' => 'roopak',
                'second_name' => 'mr',
                'gender' => 'male',
                'department' => 'cs',
                'adm_no' => '1340',
                'dob' => '1994-06-11',
                'phone' => '5687834567',
                'email' => 'roopakmr2501@gmail.com',
                'password' => Hash::make('password'),
                'distance' => '40',
                'house' => 'melekulambil',
                'street' => 'south kondazhi',
                'post' => 'kondazhy',
                'district' => 'thrissur',
                'state' => 'kerala',
                'country' => 'india',
                'guardian' => 'ramankutty',
                'guardian_phone' => '8757575788',
                'pwd' => 'no',
                'course_duration' => '2',
                'adm_date' => '2023-07-19',
                'course_type' => 'pg',
                'reservation' => 'sc',
                'image' => 'users/img/profile/1815121959-andre.jpg',
            ],

            [
                'first_name' => 'kavya',
                'second_name' => 'pp',
                'gender' => 'female',
                'department' => 'malayalam',
                'adm_no' => '1401',
                'dob' => '1995-04-08',
                'phone' => '5687434567',
                'email' => 'rkkr2530@gmail.com',
                'password' => Hash::make('password'),
                'distance' => '40',
                'house' => 'palamparambath',
                'street' => 'urngattiri',
                'post' => 'urngattiri',
                'district' => 'malappuram',
                'state' => 'kerala',
                'country' => 'india',
                'guardian' => 'narayanankutty',
                'guardian_phone' => '8076467456',
                'pwd' => 'no',
                'course_duration' => '2',
                'adm_date' => '2023-07-19',
                'course_type' => 'phd',
                'reservation' => 'gen',
                'image' => 'users/img/profile/1815121959-andre.jpg',
            ],

            [
                'first_name' => 'sansi',
                'second_name' => 'pt',
                'gender' => 'female',
                'department' => 'cs',
                'adm_no' => '1245',
                'dob' => '1996-05-01',
                'phone' => '5648534567',
                'email' => 'andreiniesta@gmail.com',
                'password' => Hash::make('password'),
                'distance' => '40',
                'house' => '12B',
                'street' => 'kolathara',
                'post' => 'kolathara',
                'district' => 'kozhikode',
                'state' => 'kerala',
                'country' => 'india',
                'guardian' => 'mustafa',
                'guardian_phone' => '898989898989',
                'pwd' => 'no',
                'course_duration' => '2',
                'adm_date' => '2023-07-19',
                'course_type' => 'pg',
                'reservation' => 'obc',
                'image' => 'users/img/profile/1815121959-andre.jpg',
            ],

            [
                'first_name' => 'shahina',
                'second_name' => 'kv',
                'gender' => 'female',
                'department' => 'mcom',
                'adm_no' => '1425',
                'dob' => '1996-04-11',
                'phone' => '56874566467',
                'email' => 'andreiniesta@gmail.com',
                'password' => Hash::make('password'),
                'distance' => '40',
                'house' => 'arakkal',
                'street' => 'pannimattam',
                'post' => 'puliyoor',
                'district' => 'kozhikode',
                'state' => 'kerala',
                'country' => 'india',
                'guardian' => 'saalim',
                'guardian_phone' => '898989898989',
                'pwd' => 'no',
                'course_duration' => '2',
                'adm_date' => '2023-07-19',
                'course_type' => 'pg',
                'reservation' => 'obc',
                'image' => 'users/img/profile/1815121959-andre.jpg',
            ]
        ]);
    }
}
